In [1]:
#!/usr/bin/env python
# coding: utf-8

In[3]:

In [2]:
import numpy as np
import pandas as pd

# Creating dataframes<br>
<br>
koi be tabular data hai jb hum usay pandas mei load krty hai tu dataframe ke tarah act krta hai.jis ko hum table bolaty hai pandas use ko dataframe bolata hai......2d structure of data using rows and columns.dataframe ky andar jo har single column hoo ga usay series bolaya jata hai...... also dataframe ke har single row is also a series

# using list:

In[4]:

In [3]:
data = [
    
    [100 , 140 , 16],
    [98 , 134 , 34],
    [45 , 67 , 23],
    [67, 190 , 45]
]

In [4]:
list_students =pd.DataFrame(data , columns = ['iq' , 'marks' , 'package'])

utomatically index generates

In[5]:

In [5]:
data = [
    
    [100 , 140 , 16],
    [98 , 134 , 34],
    [45 , 67 , 23],
    [67, 190 , 45]
]

In [6]:
list_students = pd.DataFrame(data , columns = ['iq' , 'marks' , 'package'] , index = ['student1' , 'student2' , 'student3' , 'student4'])

In[6]:

In [7]:
type(list_students)

pandas.core.frame.DataFrame

# using dict:

In[7]:

In [8]:
dict_data = {
    
    'iq' : [100 , 98 , 45 , 67],
    'marks' : [140 , 134 , 67 , 23],
    'package' : [16 , 34 , 23 , 45]
    
}

In [9]:
students = pd.DataFrame(dict_data)

In[8]:

In [10]:
dict_data = {
    
    'iq' : [100 , 98 , 45 , 67],
    'marks' : [140 , 134 , 67 , 23],
    'package' : [16 , 34 , 23 , 45]
    
}

In [11]:
students=pd.DataFrame(dict_data , index = ['student1' , 'student2' , 'student3' , 'student4'])

In[9]:

In [12]:
type(students)

pandas.core.frame.DataFrame

# read_csv

In[10]:

In [13]:
movies = pd.read_csv('D:/Data_science/data_sets/datasets-session-17/movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In[11]:

In [14]:
ipl = pd.read_csv('D:/Data_science/data_sets/datasets-session-17/ipl-matches.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# Dataframe Attributes and Methods:

# shape

In[12]:

In [15]:
movies.shape

(1629, 18)

In[13]:

In [16]:
ipl.shape

(950, 20)

# dtypes<br>
<br>
dataframe consists of series.....or series ka alg alg datatype hoo ga

In[14]:

In [17]:
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In[15]:

In [18]:
ipl.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

# index

In[16]:

In [19]:
movies.index

RangeIndex(start=0, stop=1629, step=1)

In[17]:

In [20]:
ipl.index

RangeIndex(start=0, stop=950, step=1)

# columns

In[18]:

In [21]:
movies.columns          #-----------------> given in list

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In[19]:

In [22]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

# values

In[20]:

In [23]:
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

In[21]:

In [24]:
ipl.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
       [335983, 'Chandigarh', '2008-04-19', ...,
        "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']",
        'MR Benson', 'SL Shastri'],
       [335982, 'Bangalore', '2008-04-18', ...,
        "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']",
        'Asad Rauf', 'RE Koertzen']], dtype=object)

# head and tail

In[22]:

In [25]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In[23]:

In [26]:
movies.tail()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

# sample<br>
<br>
randomly gives one row

In[24]:

In [27]:
movies.sample()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1589,Chandni Bar,tt0267363,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chandni_Bar,Chandni Bar,Chandni Bar,0,2001,150,Crime|Drama,7.6,2284,Mumtaz is a village girl whose family is kille...,A displaced woman is forced to become a beer-b...,NaN,Tabu|Atul Kulkarni|Rajpal Yadav|Shri Vallabh V...,7 wins & 14 nominations,28 September 2001 (India)

In[25]:

In [28]:
ipl.sample()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
576,598050,Mumbai,2013-05-07,2013,53,Mumbai Indians,Kolkata Knight Riders,Wankhede Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,65.0,NaN,SR Tendulkar,"['DR Smith', 'SR Tendulkar', 'KD Karthik', 'RG...","['MS Bisla', 'G Gambhir', 'JH Kallis', 'YK Pat...",HDPK Dharmasena,S Ravi

# info

In[26]:

In [29]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

n tagline values are missing......

In[27]:

In [30]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

# describe<br>
<br>
jis jis column mei mathematical operations perform hoo sakhty hai woo show kr dein ga

In[28]:

In [31]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In[29]:

In [32]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

# isnull()<br>
<br>
shows the boolean (True false)--------->where null value it gives null

In[30]:

In [33]:
movies.isnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In[31]:

In [34]:
movies.isnull().sum()           #It tell how much null values

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In[32]:

In [35]:
ipl.isnull()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
946,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
947,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
948,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
949,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In[33]:

In [36]:
ipl.isnull().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

# duplicated

In[34]:

In [37]:
movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In[35]:

In [38]:
movies.duplicated().sum()

0

In[36]:

In [39]:
ipl.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
945    False
946    False
947    False
948    False
949    False
Length: 950, dtype: bool

In[37]:

In [40]:
ipl.duplicated().sum()

0

In[38]:

In [41]:
dict_data = {
    
    'iq' : [100 , 98 , 45 , 67 , 0 , 0],
    'marks' : [140 , 134 , 67 , 23 , 0 , 0],
    'package' : [16 , 34 , 23 , 45 , 0 , 0]
    
}

In [42]:
students = pd.DataFrame(dict_data)

In [43]:
students

    iq  marks  package
0  100    140       16
1   98    134       34
2   45     67       23
3   67     23       45
4    0      0        0
5    0      0        0

In[39]:

In [44]:
students.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In[40]:

In [45]:
students.duplicated().sum()         # ONE ROW IS DUPLICATED

1

# rename

In[41]:

In [46]:
students.rename(columns = {'marks' : 'percent','package' : 'LPA'})    #------------> not permanent changes

    iq  percent  LPA
0  100      140   16
1   98      134   34
2   45       67   23
3   67       23   45
4    0        0    0
5    0        0    0

# permanent changes krne hai tu

In[42]:

In [47]:
students.rename(columns = {'marks' : 'percent','package' : 'LPA'} , inplace = 'True')

In[43]:

In [48]:
students

    iq  percent  LPA
0  100      140   16
1   98      134   34
2   45       67   23
3   67       23   45
4    0        0    0
5    0        0    0

# math methods:

# sum<br>
<br>
sum the column even strings it can concatenate

In[44]:

In [49]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In[45]:

In [50]:
movies.sum()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_2720\2790600498.py:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  movies.sum()

title_x            Uri: The Surgical StrikeBattalion 609The Accid...
imdb_id            tt8291224tt9472208tt6986710tt8108208tt6028796t...
wiki_link          https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y            Uri: The Surgical StrikeBattalion 609The Accid...
original_title     Uri: The Surgical StrikeBattalion 609The Accid...
is_adult                                                           0
year_of_release                                              3274720
runtime            1381311121211029710910414812013415314313014311...
genres             Action|Drama|WarWarBiography|DramaCrime|DramaD...
imdb_rating                                                   9053.1
imdb_votes                                                   8770965
summary            Indian army special forces execute a covert op...
dtype: object

In[46]:

In [51]:
students

    iq  percent  LPA
0  100      140   16
1   98      134   34
2   45       67   23
3   67       23   45
4    0        0    0
5    0        0    0

In[47]:

In [52]:
students.sum()

iq         310
percent    364
LPA        118
dtype: int64

In[48]:

In [53]:
students.sum(axis = 0)

iq         310
percent    364
LPA        118
dtype: int64

In[49]:

In [54]:
students.sum(axis = 1)

0    256
1    266
2    135
3    135
4      0
5      0
dtype: int64

# mean

In[50]:

In [55]:
students.mean()

iq         51.666667
percent    60.666667
LPA        19.666667
dtype: float64

# median

In[51]:

In [56]:
students.median()

iq         56.0
percent    45.0
LPA        19.5
dtype: float64

# mode

In[52]:

In [57]:
students.mode()

   iq  percent  LPA
0   0        0    0

# min

In[53]:

In [58]:
students.min()

iq         0
percent    0
LPA        0
dtype: int64

# max

In[54]:

In [59]:
students.max()

iq         100
percent    140
LPA         45
dtype: int64

# std

In[55]:

In [60]:
students.std()

iq         44.947377
percent    64.017706
LPA        18.140195
dtype: float64

# var

In[56]:

In [61]:
students.var()

iq         2020.266667
percent    4098.266667
LPA         329.066667
dtype: float64

# Selecting col from dataframe

# single column<br>
<br>
<br>
ak single column series hota ha

In[57]:

In [62]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In[58]:

In [63]:
movies['title_x']

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In[59]:

In [64]:
type(movies['title_x'])

pandas.core.series.Series

In[60]:

In [65]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In[61]:

In [66]:
ipl['WinningTeam']

0                   Gujarat Titans
1                 Rajasthan Royals
2      Royal Challengers Bangalore
3                   Gujarat Titans
4                     Punjab Kings
                  ...
945          Kolkata Knight Riders
946    Royal Challengers Bangalore
947               Delhi Daredevils
948            Chennai Super Kings
949          Kolkata Knight Riders
Name: WinningTeam, Length: 950, dtype: object

type(ipl['WinningTeam'])

# multiple columns

In[62]:

In [67]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In[63]:

In [68]:
movies[['poster_path' , 'title_y' ,'title_x' ]]

,poster_path,title_y,title_x
0,https://upload.wikimedia.org/wikipedia/en/thum...,Uri: The Surgical Strike,Uri: The Surgical Strike
1,NaN,Battalion 609,Battalion 609
2,https://upload.wikimedia.org/wikipedia/en/thum...,The Accidental Prime Minister,The Accidental Prime Minister (film)
3,https://upload.wikimedia.org/wikipedia/en/thum...,Why Cheat India,Why Cheat India
4,NaN,Evening Shadows,Evening Shadows
...,...,...,...
1624,https://upload.wikimedia.org/wikipedia/en/2/2b...,Tera Mera Saath Rahen,Tera Mera Saath Rahen
1625,https://upload.wikimedia.org/wikipedia/en/thum...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar
1626,NaN,Sabse Bada Sukh,Sabse Bada Sukh
1627,https://upload.wikimedia.org/wikipedia/en/thum...,Daaka,Daaka
1628,https://upload.wikimedia.org/wikipedia/en/thum...,Humsafar,Humsafar

In[64]:

In [69]:
type(movies[['poster_path' , 'title_y' ,'title_x' ]])

pandas.core.frame.DataFrame

# one column series hoo ge or multiple column dataframe hoo ga

In[65]:

In [70]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In[66]:

In [71]:
ipl[['Team1' , 'Team2' ,'WinningTeam' ]]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

# Selecting rows from dataframe

In[67]:

In [72]:
dict_data = {
     'name' : ['kainat' , 'maryam' , 'alisha' , 'ayesha' , 'abeera' , 'alia'],
    'iq' : [100 , 98 , 45 , 67 , 0 , 0],
    'marks' : [140 , 134 , 67 , 23 , 0 , 0],
    'package' : [16 , 34 , 23 , 45 , 0 , 0]
    
}

In [73]:
students = pd.DataFrame(dict_data)

In [74]:
students.set_index('name' , inplace = True)  #-----------------> by making the column as a index

In [75]:
students

         iq  marks  package
name
kainat  100    140       16
maryam   98    134       34
alisha   45     67       23
ayesha   67     23       45
abeera    0      0        0
alia      0      0        0

# iloc:<br>
    <br>
    <br>
    Searching using index positions<br>
    <br>

# loc:<br>
    <br>
    Searching using index labels

In[68]:

In [76]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In[69]:

In [77]:
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

# multiple rows

In[70]:

In [78]:
movies.iloc[0 : 5]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In[71]:

In [79]:
movies.iloc[0 : 15 : 2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)
12,Hum Chaar,tt9319812,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hum_Chaar,Hum chaar,Hum chaar,0,2019,143,Drama,5.6,183,The story of the film revolves around four col...,The story of the film revolves around four col...,NaN,Prit Kamani|Simran Sharma|Anshuman Malhotra|Tu...,NaN,15 February 2019 (India)
14,Sonchiriya,tt8108200,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sonchiriya,Sonchiriya,Sonchiriya,0,2019,143,Action|Crime|Drama,7.5,2322,This is the story of a group of rebels in Cham...,Set in the Chambal valley the film follows th...,NaN,Sushant Singh Rajput|Bhumi Pednekar|Manoj Bajp...,NaN,1 March 2019 (India)

# fancy indexing

In[72]:

In [80]:
movies.iloc[[2 , 6, 8]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)

# loc

In[73]:

In [81]:
students

         iq  marks  package
name
kainat  100    140       16
maryam   98    134       34
alisha   45     67       23
ayesha   67     23       45
abeera    0      0        0
alia      0      0        0

In[74]:

In [82]:
students.loc['alisha']

iq         45
marks      67
package    23
Name: alisha, dtype: int64

# multiple

In[75]:

In [83]:
students.loc['maryam' : 'alia']               #-------->last included

        iq  marks  package
name
maryam  98    134       34
alisha  45     67       23
ayesha  67     23       45
abeera   0      0        0
alia     0      0        0

In[76]:

In [84]:
students.loc['maryam' : 'alia' : 2]

        iq  marks  package
name
maryam  98    134       34
ayesha  67     23       45
alia     0      0        0

# fancy indexing

In[77]:

In [85]:
students.loc[['maryam' , 'ayesha' , 'alia']]

        iq  marks  package
name
maryam  98    134       34
ayesha  67     23       45
alia     0      0        0

In[78]:

###################   iloc is also applicable in this   ###########################################

In[79]:

In [86]:
students

         iq  marks  package
name
kainat  100    140       16
maryam   98    134       34
alisha   45     67       23
ayesha   67     23       45
abeera    0      0        0
alia      0      0        0

In[80]:

In [87]:
students.iloc[1]

iq          98
marks      134
package     34
Name: maryam, dtype: int64

# students.iloc['alisha']   ----------------> not possible

In[81]:

In [88]:
students.iloc[1 : 5]

        iq  marks  package
name
maryam  98    134       34
alisha  45     67       23
ayesha  67     23       45
abeera   0      0        0

In[82]:

In [89]:
students.iloc[0 : 5 : 2]

         iq  marks  package
name
kainat  100    140       16
alisha   45     67       23
abeera    0      0        0

# selecting both rows and columns

In[83]:

In [90]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In[85]:

In [91]:
movies.iloc[0:3 , 0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In[87]:

In [92]:
movies.loc[0:2 , 'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

# Filtering a dataframe

In [93]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

# Find all final winners

In [94]:
new_data = ipl[ipl['MatchNumber'] == 'Final']

In [95]:
new_data

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
194,1181768,Hyderabad,2019-05-12,2019,Final,Mumbai Indians,Chennai Super Kings,Rajiv Gandhi International Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",IJ Gould,Nitin Menon
254,1136620,Mumbai,2018-05-27,2018,Final,Sunrisers Hyderabad,Chennai Super Kings,Wankhede Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,8.0,NaN,SR Watson,"['SP Goswami', 'S Dhawan', 'KS Williamson', 'S...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",M Erasmus,S Ravi
314,1082650,Hyderabad,2017-05-21,2017,Final,Mumbai Indians,Rising Pune Supergiant,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,KH Pandya,"['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...","['AM Rahane', 'RA Tripathi', 'SPD Smith', 'MS ...",NJ Llong,S Ravi
373,981019,Bangalore,2016-05-29,2016,Final,Royal Challengers Bangalore,Sunrisers Hyderabad,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,8.0,NaN,BCJ Cutting,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...","['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...",HDPK Dharmasena,BNJ Oxenford
433,829823,Kolkata,2015-05-24,2015,Final,Mumbai Indians,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,N,Mumbai Indians,Runs,41.0,NaN,RG Sharma,"['LMP Simmons', 'PA Patel', 'RG Sharma', 'KA P...","['DR Smith', 'MEK Hussey', 'SK Raina', 'MS Dho...",HDPK Dharmasena,RK Illingworth
492,734049,Bangalore,2014-06-01,2014,Final,Kolkata Knight Riders,Kings XI Punjab,M Chinnaswamy Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,3.0,NaN,MK Pandey,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'...",HDPK Dharmasena,BNJ Oxenford
552,598073,Kolkata,2013-05-26,2013,Final,Chennai Super Kings,Mumbai Indians,Eden Gardens,Mumbai Indians,bat,N,Mumbai Indians,Runs,23.0,NaN,KA Pollard,"['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...","['DR Smith', 'AP Tare', 'KD Karthik', 'RG Shar...",HDPK Dharmasena,SJA Taufel
628,548381,Chennai,2012-05-27,2012,Final,Kolkata Knight Riders,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,MS Bisla,"['MS Bisla', 'G Gambhir', 'JH Kallis', 'LR Shu...","['MEK Hussey', 'M Vijay', 'SK Raina', 'MS Dhon...",BF Bowden,SJA Taufel
702,501271,Chennai,2011-05-28,2011,Final,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,58.0,NaN,M Vijay,"['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...",Asad Rauf,SJA Taufel
775,419165,Mumbai,2010-04-25,2009/10,Final,Chennai Super Kings,Mumbai Indians,Dr DY Patil Sports Academy,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,22.0,NaN,SK Raina,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['S Dhawan', 'SR Tendulkar', 'AM Nayar', 'Harb...",RE Koertzen,SJA Taufel
835,392239,Johannesburg,2009-05-24,2009,Final,Royal Challengers Bangalore,Deccan Chargers,New Wanderers Stadium,Royal Challengers Bangalore,field,N,Deccan Chargers,Runs,6.0,NaN,A Kumble,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy...",RE Koertzen,SJA Taufel
892,336040,Mumbai,2008-06-01,2007/08,Final,Chennai Super Kings,Rajasthan Royals,Dr DY Patil Sports Academy,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['PA Patel', 'S Vidyut', 'SK Raina', 'JA Morke...","['NK Patel', 'SA Asnodkar', 'Kamran Akmal', 'S...",BF Bowden,RE Koertzen

In [96]:
new_data[['Season' , 'WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

# also write in one line

In [97]:
new_data = ipl[ipl['MatchNumber'] == 'Final'][['Season' , 'WinningTeam']]

In [98]:
new_data

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

# how many super over finishes have occured

In [99]:
ipl.head(3)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [100]:
ipl['SuperOver'] == 'Y'

0      False
1      False
2      False
3      False
4      False
       ...
945    False
946    False
947    False
948    False
949    False
Name: SuperOver, Length: 950, dtype: bool

In [101]:
ipl[ipl['SuperOver']== 'Y']

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
114,1254077,Chennai,2021-04-25,2021,20,Delhi Capitals,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,bat,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SPD Smith'...","['DA Warner', 'JM Bairstow', 'KS Williamson', ...",CB Gaffaney,KN Ananthapadmanabhan
158,1216512,Abu Dhabi,2020-10-18,2020/21,35,Kolkata Knight Riders,Sunrisers Hyderabad,Sheikh Zayed Stadium,Sunrisers Hyderabad,field,Y,Kolkata Knight Riders,SuperOver,NaN,NaN,LH Ferguson,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'AD ...","['JM Bairstow', 'KS Williamson', 'PK Garg', 'D...",PG Pathak,S Ravi
159,1216517,NaN,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Dubai International Cricket Stadium,Mumbai Indians,bat,Y,Kings XI Punjab,SuperOver,NaN,NaN,KL Rahul,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",Nitin Menon,PR Reiffel
184,1216547,NaN,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,AB de Villiers,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",Nitin Menon,PR Reiffel
192,1216493,NaN,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Kings XI Punjab,field,Y,Delhi Capitals,SuperOver,NaN,NaN,MP Stoinis,"['PP Shaw', 'S Dhawan', 'SO Hetmyer', 'SS Iyer...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",AK Chaudhary,Nitin Menon
203,1178426,Mumbai,2019-05-02,2019,51,Mumbai Indians,Sunrisers Hyderabad,Wankhede Stadium,Mumbai Indians,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,JJ Bumrah,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'E Lewi...","['WP Saha', 'MJ Guptill', 'MK Pandey', 'KS Wil...",CK Nandan,S Ravi
244,1175365,Delhi,2019-03-30,2019,10,Kolkata Knight Riders,Delhi Capitals,Arun Jaitley Stadium,Delhi Capitals,field,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['NS Naik', 'CA Lynn', 'RV Uthappa', 'N Rana',...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",AY Dandekar,Nitin Menon
339,1082625,Rajkot,2017-04-29,2017,35,Gujarat Lions,Mumbai Indians,Saurashtra Cricket Association Stadium,Gujarat Lions,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,KH Pandya,"['Ishan Kishan', 'BB McCullum', 'SK Raina', 'A...","['PA Patel', 'JC Buttler', 'N Rana', 'RG Sharm...",AK Chaudhary,CB Gaffaney
474,829741,Ahmedabad,2015-04-21,2015,18,Rajasthan Royals,Kings XI Punjab,"Sardar Patel Stadium, Motera",Kings XI Punjab,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,SE Marsh,"['AM Rahane', 'SR Watson', 'DJ Hooda', 'SPD Sm...","['M Vijay', 'V Sehwag', 'SE Marsh', 'GJ Maxwel...",M Erasmus,S Ravi
533,729315,Abu Dhabi,2014-04-29,2014,19,Kolkata Knight Riders,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,bat,Y,Rajasthan Royals,SuperOver,NaN,NaN,JP Faulkner,"['G Gambhir', 'MS Bisla', 'JH Kallis', 'MK Pan...","['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...",Aleem Dar,AK Chaudhary
608,598017,Bangalore,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,V Kohli,"['CH Gayle', 'KL Rahul', 'V Kohli', 'AB de Vil...","['DA Warner', 'V Sehwag', 'MC Juneja', 'DPMD J...",M Erasmus,VA Kulkarni
621,598004,Hyderabad,2013-04-07,2013,7,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,bat,Y,Sunrisers Hyderabad,SuperOver,NaN,NaN,GH Vihari,"['PA Reddy', 'PA Patel', 'CL White', 'GH Vihar...","['CH Gayle', 'TM Dilshan', 'V Kohli', 'KK Nair...",AK Chaudhary,S Ravi
819,419121,Chennai,2010-03-21,2009/10,16,Chennai Super Kings,Kings XI Punjab,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,J Theron,"['PA Patel', 'ML Hayden', 'SK Raina', 'M Vijay...","['RS Bopara', 'IK Pathan', 'KC Sangakkara', 'D...",K Hariharan,DJ Harper
883,392190,Cape Town,2009-04-23,2009,10,Kolkata Knight Riders,Rajasthan Royals,Newlands,Kolkata Knight Riders,field,Y,Rajasthan Royals,SuperOver,NaN,NaN,YK Pathan,"['CH Gayle', 'BB McCullum', 'LR Shukla', 'BJ H...","['GC Smith', 'PC Valthaty', 'RJ Quiney', 'YK P...",MR Benson,M Erasmus

# how many superover matches use shape to get number of rows

In [102]:
ipl[ipl['SuperOver']== 'Y'].shape

(14, 20)

In [103]:
ipl[ipl['SuperOver']== 'Y'].shape[0]

14

# how many matches has csk won in kolkata

In [104]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [112]:
ipl['City'] == 'Kolkata'

0      False
1      False
2       True
3       True
4      False
       ...
945     True
946    False
947    False
948    False
949    False
Name: City, Length: 950, dtype: bool

In [113]:
ipl[ipl['City'] == 'Kolkata']

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,city
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,kolkata
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,kolkata
207,1178422,Kolkata,2019-04-28,2019,47,Kolkata Knight Riders,Mumbai Indians,Eden Gardens,Mumbai Indians,field,...,Kolkata Knight Riders,Runs,34.0,NaN,AD Russell,"['Shubman Gill', 'CA Lynn', 'AD Russell', 'KD ...","['Q de Kock', 'RG Sharma', 'E Lewis', 'SA Yada...",IJ Gould,Nitin Menon,kolkata
211,1178418,Kolkata,2019-04-25,2019,43,Kolkata Knight Riders,Rajasthan Royals,Eden Gardens,Rajasthan Royals,field,...,Rajasthan Royals,Wickets,3.0,NaN,VR Aaron,"['CA Lynn', 'Shubman Gill', 'N Rana', 'KD Kart...","['AM Rahane', 'SV Samson', 'SPD Smith', 'BA St...",AY Dandekar,IJ Gould,kolkata
219,1178410,Kolkata,2019-04-19,2019,35,Royal Challengers Bangalore,Kolkata Knight Riders,Eden Gardens,Kolkata Knight Riders,field,...,Royal Challengers Bangalore,Runs,10.0,NaN,V Kohli,"['PA Patel', 'V Kohli', 'AD Nath', 'MM Ali', '...","['CA Lynn', 'SP Narine', 'Shubman Gill', 'RV U...",IJ Gould,Nitin Menon,kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
908,336025,Kolkata,2008-05-18,2007/08,41,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,...,Chennai Super Kings,Runs,3.0,D/L,M Ntini,"['Salman Butt', 'Mohammad Hafeez', 'SC Ganguly...","['PA Patel', 'SP Fleming', 'S Vidyut', 'SK Rai...",Asad Rauf,K Hariharan,kolkata
915,336017,Kolkata,2008-05-13,2007/08,35,Kolkata Knight Riders,Delhi Daredevils,Eden Gardens,Kolkata Knight Riders,bat,...,Kolkata Knight Riders,Runs,23.0,NaN,Shoaib Akhtar,"['Salman Butt', 'A Chopra', 'SC Ganguly', 'DJ ...","['G Gambhir', 'V Sehwag', 'AB de Villiers', 'M...",Asad Rauf,IL Howell,kolkata
922,336010,Kolkata,2008-05-08,2007/08,29,Kolkata Knight Riders,Royal Challengers Bangalore,Eden Gardens,Kolkata Knight Riders,bat,...,Kolkata Knight Riders,Runs,5.0,NaN,SC Ganguly,"['A Chopra', 'BJ Hodge', 'SC Ganguly', 'DJ Hus...","['J Arunkumar', 'S Chanderpaul', 'MV Boucher',...",Asad Rauf,IL Howell,kolkata
934,335997,Kolkata,2008-04-29,2007/08,16,Kolkata Knight Riders,Mumbai Indians,Eden Gardens,Kolkata Knight Riders,bat,...,Mumbai Indians,Wickets,7.0,NaN,ST Jayasuriya,"['BB McCullum', 'SC Ganguly', 'RT Ponting', 'D...","['AM Rahane', 'ST Jayasuriya', 'MK Pandey', 'R...",BF Bowden,AV Jayaprakash,kolkata
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,kolkata

In [121]:
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')]    #------------------> bitwise and (used for binary operations)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,city
224,1178404,Kolkata,2019-04-14,2019,29,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,...,Chennai Super Kings,Wickets,5.0,NaN,Imran Tahir,"['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",CK Nandan,RJ Tucker,kolkata
602,598022,Kolkata,2013-04-20,2013,26,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,...,Chennai Super Kings,Wickets,4.0,NaN,RA Jadeja,"['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...","['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...",Asad Rauf,AK Chaudhary,kolkata
641,548368,Kolkata,2012-05-14,2012,63,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,field,...,Chennai Super Kings,Wickets,5.0,NaN,MEK Hussey,"['G Gambhir', 'BB McCullum', 'JH Kallis', 'MK ...","['MEK Hussey', 'M Vijay', 'SK Raina', 'F du Pl...",JD Cloete,SJA Taufel,kolkata
827,419113,Kolkata,2010-03-16,2009/10,8,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Chennai Super Kings,bat,...,Chennai Super Kings,Runs,55.0,NaN,MS Dhoni,"['BJ Hodge', 'MK Tiwary', 'SC Ganguly', 'WP Sa...","['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...",HDPK Dharmasena,AM Saheba,kolkata
908,336025,Kolkata,2008-05-18,2007/08,41,Kolkata Knight Riders,Chennai Super Kings,Eden Gardens,Kolkata Knight Riders,bat,...,Chennai Super Kings,Runs,3.0,D/L,M Ntini,"['Salman Butt', 'Mohammad Hafeez', 'SC Ganguly...","['PA Patel', 'SP Fleming', 'S Vidyut', 'SK Rai...",Asad Rauf,K Hariharan,kolkata

In [119]:
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')].shape

(5, 21)

In [120]:
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')].shape[0]

5

# Toss  winner is a match winner in percentage

In [122]:
ipl['TossWinner'] == ipl['WinningTeam']

0      False
1       True
2      False
3       True
4      False
       ...
945    False
946    False
947    False
948     True
949    False
Length: 950, dtype: bool

In [127]:
ipl[ipl['TossWinner'] == ipl['WinningTeam']]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,city
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,kolkata
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,kolkata
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,...,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma,kolkata
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,...,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde,kolkata
11,1304109,Mumbai,2022-05-15,2022,63,Rajasthan Royals,Lucknow Super Giants,"Brabourne Stadium, Mumbai",Rajasthan Royals,bat,...,Rajasthan Royals,Runs,24.0,NaN,TA Boult,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['Q de Kock', 'KL Rahul', 'A Badoni', 'DJ Hood...",PG Pathak,Tapan Sharma,kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,335996,Bangalore,2008-04-28,2007/08,15,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Chennai Super Kings,bat,...,Chennai Super Kings,Runs,13.0,NaN,MS Dhoni,"['B Chipli', 'W Jaffer', 'LRPL Taylor', 'JH Ka...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'SK Ra...",BR Doctrove,RB Tiffin,kolkata
937,335994,Mumbai,2008-04-27,2007/08,14,Mumbai Indians,Deccan Chargers,Dr DY Patil Sports Academy,Deccan Chargers,field,...,Deccan Chargers,Wickets,10.0,NaN,AC Gilchrist,"['L Ronchi', 'ST Jayasuriya', 'AM Rahane', 'RV...","['AC Gilchrist', 'VVS Laxman', 'A Symonds', 'R...",Asad Rauf,SL Shastri,kolkata
939,335992,Bangalore,2008-04-26,2007/08,12,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,SR Watson,"['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...","['GC Smith', 'M Rawat', 'YK Pathan', 'SR Watso...",MR Benson,IL Howell,kolkata
941,335990,Hyderabad,2008-04-24,2007/08,9,Deccan Chargers,Rajasthan Royals,"Rajiv Gandhi International Stadium, Uppal",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['AC Gilchrist', 'VVS Laxman', 'Shahid Afridi'...","['Kamran Akmal', 'GC Smith', 'YK Pathan', 'SR ...",Asad Rauf,MR Benson,kolkata
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,kolkata

In [129]:
ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]

489

In [131]:
(ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]/ipl.shape[0])* 100

51.473684210526315

# movies with rating higher than 8 and votes > 10000

In [133]:
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

In [134]:
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] > 10000)]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
40,Super 30 (film),tt7485048,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Super_30_(film),Super 30,Super 30,0,2019,154,Biography|Drama,8.2,13972,Anand Kumar a Mathematics genius from a modes...,Based on life of Patna-based mathematician Ana...,Inspired by the Life of Anand Kumar & His Stud...,Hrithik Roshan|Mrunal Thakur|Nandish Singh|Vir...,NaN,12 July 2019 (USA)
143,Tumbbad,tt8239946,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tumbbad,Tumbbad,Tumbbad,0,2018,104,Drama|Fantasy|Horror,8.2,16535,Set in Tumbbad in the 1920s the story revolve...,A mythological story about a goddess who creat...,NaN,Sohum Shah|Jyoti Malshe|Anita Date|Ronjini Cha...,9 wins & 12 nominations,12 October 2018 (India)
146,Andhadhun,tt8108198,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Andhadhun,Andhadhun,Andhadhun,0,2018,139,Crime|Thriller,8.4,51615,Akash a blind pianist is preparing for a Londo...,A series of mysterious events changes the life...,NaN,Ayushmann Khurrana|Tabu|Radhika Apte|Anil Dhaw...,24 wins & 25 nominations,5 October 2018 (USA)
325,Pink (2016 film),tt5571734,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pink_(2016_film),Pink,Pink,0,2016,136,Drama|Thriller,8.2,33902,Deepak is a lawyer suffering from bipolar diso...,When three young women are implicated in a cri...,NaN,Taapsee Pannu|Amitabh Bachchan|Kirti Kulhari|A...,12 wins & 14 nominations,16 September 2016 (USA)
354,Dangal (film),tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Aamir Khan|Fatima Sana Shaikh|Sanya Malhotra|S...,23 wins & 4 nominations,21 December 2016 (USA)
418,Masaan,tt4635372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fly_Away_Solo,Masaan,Masaan,0,2015,109,Drama,8.1,19904,Four lives intersect along the Ganges: a low c...,Four lives intersect along the Ganges: a low c...,Paths of grieve intersect on the Ganges River.,Richa Chadha|Sanjay Mishra|Vicky Kaushal|Panka...,20 wins & 5 nominations,24 July 2015 (India)
426,Drishyam (2015 film),tt4430212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Drishyam(2015),Drishyam,Drishyam,0,2015,163,Crime|Drama|Mystery,8.2,58340,Vijay Salgaonkar runs a cable TV network in a ...,Desperate measures are taken by a man who trie...,Remake of a Malayalam movie,Ajay Devgn|Shriya Saran|Tabu|Rajat Kapoor|Ishi...,1 win & 1 nomination,31 July 2015 (USA)
436,Talvar (film),tt4934950,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Talvar_(film),Talvar,Talvar,0,2015,132,Crime|Drama|Mystery,8.2,26612,The story revolves around the mysterious murde...,An experienced investigator confronts several ...,NaN,Irrfan Khan|Konkona Sen Sharma|Neeraj Kabi|Soh...,7 wins & 11 nominations,2 October 2015 (USA)
469,Queen (2014 film),tt3322420,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Queen_(2014_film),Queen,Queen,0,2013,146,Comedy|Drama,8.2,56406,Queen is a movie about growing up. Rani (Kanga...,A Delhi girl from a traditional family sets ou...,Everything in life happens for the good.,Kangana Ranaut|Rajkummar Rao|Lisa Haydon|Jeffr...,21 wins & 14 nominations,7 March 2014 (India)
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
566,Ugly (film),tt2882328,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ugly_(film),Ugly,Ugly,0,2013,128,Crime|Drama|Mystery,8.1,17483,The film portrays the kidnapping of a little g...,The case of a missing girl takes us through a ...,NaN,Rahul Bhat|Ronit Roy|Tejaswini Kolhapure|Viine...,3 wins & 12 nominations,26 December 2014 (India)
567,PK (film),tt2338151,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/PK_(film),PK,PK,0,2014,153,Comedy|Drama|Fantasy,8.1,143605,P. K. is a comedy of ideas about a stranger in...,An alien on Earth loses the only device he can...,NaN,Aamir Khan|Anushka Sharma|Saurabh Shukla|Sanja...,14 wins & 15 nominations,19 December 2014 (India)
589,Vishwaroopam,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Kamal Haasan|Rahul Bose|Shekhar Kapur|Pooja Ku...,5 wins & 11 nominations,25 January 2013 (India)
612,Bhaag Milkha Bhaag,tt2356180,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhaag_Milkha_Bhaag,Bhaag Milkha Bhaag,Bhaag Milkha Bhaag,0,2013,186,Biography|Drama|Sport,8.2,56205,"The true story of the ""Flying Sikh"" - world ch...",The truth behind the ascension of Milkha Singh...,The story unfolds July 12| 2013.,Farhan Akhtar|Sonam Kapoor|Pavan Malhotra|Art ...,52 wins & 34 nominations,12 July 2013 (USA)
638,Shahid (film),tt2181831,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Shahid_(film),Shahid,Shahid,0,2012,129,Biography|Crime|Drama,8.3,13537,Shahid traces the true story of slain human ri...,The account of Human Rights lawyer Shahid Azmi...,Based On The Life Of One Of The Most Controver...,Rajkummar Rao|Mohammed Zeeshan Ayyub|Baljinder...,10 wins & 6 nominations,18 October 2013 (India)
668,Paan Singh Tomar (film),tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Irrfan Khan|,10 wins & 11 nominations,2 March 2012 (USA)
669,Kahaani,tt1821480,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kahaani,Kahaani,Kahaani,0,2012,122,Mystery|Thriller,8.1,53181,Kolkata is abuzz with the preparations for the...,A pregnant woman's search for her missing husb...,A mother of a story,Vidya Balan|Parambrata Chattopadhyay|Indraneil...,19 wins & 18 nominations,9 March 2012 (India)
693,Gangs of Wasseypur,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Gangs of Wasseypur – Part 2,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Manoj Bajpayee|Richa Chadha|Nawazuddin Siddiqu...,12 wins & 43 nominations,2 August 2012 (Singapore)
709,Barfi!,tt2082197,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Barfi!,Barfi!,Barfi!,0,2012,151,Comedy|Drama|Romance,8.1,70443,Set in the 1970s in a pretty corner of India ...,Three young people learn that love can neither...,NaN,Ranbir Kapoor|Priyanka Chopra|Ileana D'Cruz|Sa...,50 wins & 28 nominations,14 September 2012 (India)
714,OMG – Oh My God!,tt2283748,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Oh_My_God_(2012_...,OMG: Oh My God!,OMG: Oh My God!,0,2012,125,Comedy|Drama|Fantasy,8.2,46072,Kanji Lalji Mehta though an atheist owns a s...,A shopkeeper takes God to court when his shop ...,Kanjibhai is taking God to court!,Paresh Rawal|Akshay Kumar|Mithun Chakraborty|O...,5 wins & 11 nominations,28 September 2012 (India)
778,Zindagi Na Milegi Dobara,tt1562872,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zindagi_Na_Mileg...,Zindagi Na Milegi Dobara,Zindagi Na Milegi Dobara,0,2011,155,Comedy|Drama,8.1,60826,Three friends decide to turn their fantasy vac...,Three friends decide to turn their fantasy vac...,NaN,Hrithik Roshan|Farhan Akhtar|Abhay Deol|Katrin...,30 wins & 22 nominations,15 July 2011 (India)
869,Udaan (2010 film),tt1639426,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Udaan_(2010_film),Udaan,Udaan,0,2010,134,Drama,8.2,39567,After being abandoned for eight straight years...,Expelled from his school a 16-year old boy re...,NaN,Rajat Barmecha|Ronit Roy|Manjot Singh|Ram Kapo...,13 wins & 13 nominations,16 July 2010 (India)
912,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots,3 Idiots,3 Idiots,0,2009,170,Comedy|Drama,8.4,310481,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
930,Gulaal (film),tt1261047,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gulaal_(film),Gulaal,Gulaal,0,2009,140,Crime|Drama|Thriller,8.1,12799,Bikaner-based 28-year-old Dilip Kumar Singh is...,A law student witnesses deception homicide a...,Love... Power... Revolution.,Kay Kay Menon|Raj Singh Chaudhary|Jesse Randha...,2 nominations,13 March 2009 (India)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1066,Chak De! India,tt0871510,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chak_De!_India,Chak de! India,Chak De! India,0,2007,153,Drama|Family|Sport,8.2,68421,Kabir Khan (Shahrukh Khan) knows what it's lik...,Kabir Khan is the coach of the Indian Women's ...,Sometimes Winning is Everything,Shah Rukh Khan|Vidya Malvade|Sagarika Ghatge|S...,28 wins & 13 nominations,10 August 2007 (India)
1127,Taare Zameen Par,tt0986264,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Taare_Zameen_Par,Like Stars on Earth,Taare Zameen Par,0,2007,165,Drama|Family,8.4,148498,Ishaan Awasthi is an eight-year-old child whos...,An eight-year-old boy is thought to be a lazy ...,Every Child is Special,Darsheel Safary|Aamir Khan|Tisca Chopra|Vipin ...,18 wins & 8 nominations,21 December 2007 (India)
1180,Khosla Ka Ghosla,tt0466460,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Khosla_Ka_Ghosla,Khosla Ka Ghosla!,Khosla Ka Ghosla!,0,2006,135,Comedy|Crime|Drama,8.3,20538,K.K. Khosla (Anupam Kher) is a middle class ma...,A Delhi based retired middle class man tries h...,NaN,Anupam Kher|Boman Irani|Parvin Dabas|Tara Shar...,2 nominations,22 September 2006 (India)
1183,Lage Raho Munna Bhai,tt0456144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lage_Raho_Munna_...,Carry On Munna Bhai,Lage Raho Munna Bhai,0,2006,144,Comedy|Drama|Romance,8.1,39486,A hilarious underworld gangster known as Munna...,Munna Bhai embarks on a journey with Mahatma G...,Munnabhai meets Mahatma Gandhi,Sanjay Dutt|Arshad Warsi|Vidya Balan|Boman Ira...,19 wins & 16 nominations,1 September 2006 (USA)
1188,Omkara (2006 film),tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Ajay Devgn|Saif Ali Khan|Vivek Oberoi|Kareena ...,19 wins & 20 nominations,28 July 2006 (USA)
1195,Rang De Basanti,tt0405508,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rang_De_Basanti,Rang De Basanti,Rang De Basanti,0,2006,167,Comedy|Drama,8.2,103071,Sue comes to India to make a film on Indian re...,The story of six young Indians who assist an E...,A Generation Awakens.,Aamir Khan|Siddharth|Sharman Joshi|Kunal Kapoo...,Nominated for 1 BAFTA Film Award,26 January 2006 (USA)
1223,Black (2005 film),tt0375611,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Black_(2005_film),Black,Black,0,2005,122,Drama,8.2,31658,Based in Simla the McNallys are an Anglo-Indi...,The cathartic tale of a young woman who can't ...,An unending darkness... A world of shadows... ...,Amitabh Bachchan|Rani Mukerji|Shernaz Patel|Ay...,44 wins & 4 nominations,4 February 2005 (USA)
1252,Iqbal (film),tt0453729,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Iqbal_(film),Iqbal,Iqbal,0,2005,132,Drama|Sport,8.1,14864,India - a Nation obsessed with cricket - and i...,Iqbal the deaf and mute son of a farmer has ...,NaN,Shreyas Talpade|Naseeruddin Shah|Shweta Basu P...,9 wins & 13 nominations,20 January 2006 (USA)
1384,Swades,tt0367110,https://upload.wikimedia.org/wikipedia/en/8/85...,https://en.wikipedia.org/wiki/Swades,Swades,Swades: We the People,0,2004,210,Drama,8.2,76737,Set in modern day India Swades is a film that...,A successful Indian scientist returns to an In...,We| the people,Shah Rukh Khan|Gayatri Joshi|Kishori Ballal|Sm...,14 wins & 23 nominations,17 December 2004 (India)
1403,Munna Bhai M.B.B.S.,tt0374887,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Munna_Bhai_M.B.B.S.,Munna Bhai M.B.B.S.,Munna Bhai M.B.B.S.,0,2003,156,Comedy|Drama|Musical,8.1,67148,In India gangsters are called Bhai (brothers)....,A gangster sets out to fulfill his father's dr...,He might just cure you.,Sanjay Dutt|Arshad Warsi|Gracy Singh|Sunil Dut...,19 wins & 29 nominations,19 December 2003 (India)
1554,The Legend of Bhagat Singh,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Ajay Devgn|Sushant Singh|D. Santosh|Akhilendra...,11 wins & 5 nominations,7 June 2002 (India)
1567,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1568,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1571,Dil Chahta Hai,tt0292490,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dil_Chahta_Hai,Dil Chahta Hai,Dil Chahta Hai,0,2001,183,Comedy|Drama|Romance,8.1,62313,Three young men Akash Sameer and Siddharth a...,Three inseparable childhood friends are just o...,Welcome to a summer of their lives you will ne...,Aamir Khan|Saif Ali Khan|Akshaye Khanna|Preity...,22 wins & 37 nominations,10 August 2001 (India)

In [136]:
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] > 10000)].shape[0]

43

# action movies with the rating higher than 7.5

In [137]:
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

In [140]:
movies['genres']

0       Action|Drama|War
1                    War
2        Biography|Drama
3            Crime|Drama
4                  Drama
              ...
1624               Drama
1625               Drama
1626        Comedy|Drama
1627              Action
1628       Drama|Romance
Name: genres, Length: 1629, dtype: object

In [141]:
movies['genres'].str

In [142]:
movies['genres'].str.split('|')

0       [Action, Drama, War]
1                      [War]
2         [Biography, Drama]
3             [Crime, Drama]
4                    [Drama]
                ...
1624                 [Drama]
1625                 [Drama]
1626         [Comedy, Drama]
1627                [Action]
1628        [Drama, Romance]
Name: genres, Length: 1629, dtype: object

In [144]:
mask=movies['genres'].str.split('|').apply(lambda x : 'Action' in x)

In [146]:
mask1=movies['imdb_rating'] > 7.5

In [150]:
movies[mask & mask1].shape[0]

33

In [151]:
############################# Also use

In [152]:
mask=movies['genres'].str.contains("Action")

In [153]:
mask1=movies['imdb_rating'] > 7.5

In [154]:
movies[mask & mask1].shape[0]

33

# Write a function that can return the track record of two teams against each other

In [156]:
ipl.head(3)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,city
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,kolkata
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,kolkata
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,kolkata

In [228]:
team_1=ipl[ipl['Team1']== ipl['WinningTeam']].shape
team_1

(480, 21)

In [230]:
team_2=ipl[(ipl['Team2'])== (ipl['WinningTeam'])].shape
team_2

(466, 21)

# Adding new columns:

In [185]:
movies['Country'] = 'India'

In [187]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date', 'Country'],
      dtype='object')

# existing one

In [194]:
movies['actors']
new_data =movies.dropna()

In [196]:
movies['Lead Actor'] = new_data['actors'].str.split('|').apply(lambda x : x[0])

In [197]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date', 'Country', 'Lead Actor'],
      dtype='object')

# important dataframe functions

# astype

In [198]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,city
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,kolkata
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,kolkata
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,kolkata
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,kolkata
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,kolkata
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,kolkata
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,kolkata
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,kolkata
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,kolkata

In [201]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
 20  city             950 non-null    object
dtypes: float64(1), int64(1), object(19)
memory usage: 156.0+ KB

In [202]:
ipl['ID']=ipl['ID'].astype('int32')

In [203]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
 20  city             950 non-null    object
dtypes: float64(1), int32(1), object(19)
memory usage: 152.3+ KB

In [204]:
ipl['Season'] = ipl['Season'].astype('category')

In [205]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
 20  city             950 non-null    object
dtypes: category(1), float64(1), int32(1), object(18)
memory usage: 146.4+ KB